// templates/client-vue2/src-http/App.vue
<template>
  <div class="App">
    <h1>TSRPC Guestbook</h1>

    <div class="send">
      <textarea placeholder="Say something..." v-model="input" />
      <button v-on:click="send">Send</button>
    </div>

    <ul class="list">
      <li v-for="(v, i) in list" v-bind:key="i">
        <div class="content">{{ v.content }}</div>
        <div class="time">{{ v.time.toLocaleTimeString() }}</div>
      </li>
    </ul>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { client } from "./client";
import { ResGetData } from "./shared/protocols/PtlGetData";

export interface AppData {
  input: string;
  list: ResGetData["data"];
}

export default Vue.extend({
  name: "App",
  data() {
    return {
      input: "",
      list: [],
    } as AppData;
  },

  methods: {
    async loadList() {
      let ret = await client.callApi("GetData", {});

      // Error
      if (!ret.isSucc) {
        alert(ret.err.message);
        return;
      }

      // Success
      this.list = ret.res.data;
    },

    async send() {
      let ret = await client.callApi("AddData", {
        content: this.input,
      });

      // Error
      if (!ret.isSucc) {
        alert(ret.err.message);
        return;
      }

      // Success
      this.input = "";
      this.loadList();
    },
  },

  mounted() {
    this.loadList();
  },
});
// @Component
// export default class App extends Vue {
//   input = "";
//   list: ResGetData["data"] = [];

//   async loadList(): Promise<void> {
//     let ret = await client.callApi("GetData", {});

//     // Error
//     if (!ret.isSucc) {
//       alert(ret.err.message);
//       return;
//     }

//     // Success
//     this.list = ret.res.data;
//   }

//   async send(): Promise<void> {
//     let ret = await client.callApi("AddData", {
//       content: this.input,
//     });

//     // Error
//     if (!ret.isSucc) {
//       alert(ret.err.message);
//       return;
//     }

//     // Success
//     this.input = "";
//     this.loadList();
//   }

//   mounted(): void {
//     this.loadList();
//   }
// }
</script>

<style lang="less">
@import "./App.less";
</style>

// templates/client-react/src-http/App.tsx
import { useEffect, useState } from 'react'
import { client } from './client'
import type { ResGetData } from './shared/protocols/PtlGetData'

export function App() {
  const [input, setInput] = useState('')
  const [list, setList] = useState<ResGetData['data']>([])

  // Reload message list
  async function loadList() {
    const ret = await client.callApi('GetData', {})

    if (!ret.isSucc) {
      alert(ret.err.message)
      return
    }

    setList(ret.res.data)
  }

  // Send Message
  async function send() {
    const ret = await client.callApi('AddData', {
      content: input,
    })

    if (!ret.isSucc) {
      alert(ret.err.message)
      return
    }

    setInput('')
    loadList()
  }

  // Load list at first
  useEffect(() => {
    loadList()
  }, [])

  return (
    <div className="app">
      <h1>TSRPC Guestbook</h1>
      <div className="send">
        <textarea
          placeholder="Say something..."
          value={input}
          onChange={(e) => setInput(e.target.value)}
        />
        <button onClick={send}>Send</button>
      </div>
      <ul className="list">
        {list.map((v, i) => (
          <li key={i}>
            <div className="content">{v.content}</div>
            <div className="time">{v.time.toLocaleTimeString()}</div>
          </li>
        ))}
      </ul>
    </div>
  )
}
