// templates/client-vue2/src-ws/App.vue
<template>
  <div class="App">
    <h1>Hello, TSRPC</h1>

    <div class="say-hello">
      <div class="say">
        <input
          type="text"
          class="name"
          v-model="name"
          placeholder="Input your name..."
        />
        <button class="btn-send" v-on:click="onBtnSendClick">Say Hello</button>
      </div>

      <div class="reply" v-if="reply">
        <div class="title">Server Reply</div>
        <div class="content">{{ reply }}</div>
      </div>
    </div>

    <div class="server-pushed-msg">
      <div class="title">Server Pushed Messages</div>
      <p class="hint">You can open multiple pages to see the effects</p>
      <ul>
        <li v-for="v in serverMsgs" v-bind:key="v.name">
          Welcome <b class="name">{{ v.name }}</b>
          <p class="time">{{ v.time.toTimeString().substr(0, 8) }}</p>
        </li>
      </ul>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import { MsgHello } from "./shared/protocols/MsgHello";
import { client } from "./main";

@Component
export default class App extends Vue {
  name = "";
  reply = "";
  serverMsgs: MsgHello[] = [];

  mounted(): void {
    // ========== TSRPC Client -> listenMsg ==========
    client.listenMsg("Hello", (msg) => {
      this.serverMsgs.unshift(msg);
    });
  }

  async onBtnSendClick(): Promise<void> {
    // ========== TSRPC Client -> callApi ==========
    let ret = await client.callApi("Hello", {
      name: this.name,
    });

    // Error
    if (!ret.isSucc) {
      this.reply = "";
      alert("= ERROR =\n" + ret.err.message);
      return;
    }

    // Success
    this.reply = ret.res.reply;
    this.name = "";
  }
}
</script>

<style lang="less">
@import "./App.less";
</style>

// templates/client-react/src-http/App.tsx
import { useEffect, useState } from 'react'
import { client } from './client'
import type { ResGetData } from './shared/protocols/PtlGetData'

export function App() {
  const [input, setInput] = useState('')
  const [list, setList] = useState<ResGetData['data']>([])

  // Reload message list
  async function loadList() {
    const ret = await client.callApi('GetData', {})

    if (!ret.isSucc) {
      alert(ret.err.message)
      return
    }

    setList(ret.res.data)
  }

  // Send Message
  async function send() {
    const ret = await client.callApi('AddData', {
      content: input,
    })

    if (!ret.isSucc) {
      alert(ret.err.message)
      return
    }

    setInput('')
    loadList()
  }

  // Load list at first
  useEffect(() => {
    loadList()
  }, [])

  return (
    <div className="app">
      <h1>TSRPC Guestbook</h1>
      <div className="send">
        <textarea
          placeholder="Say something..."
          value={input}
          onChange={(e) => setInput(e.target.value)}
        />
        <button onClick={send}>Send</button>
      </div>
      <ul className="list">
        {list.map((v, i) => (
          <li key={i}>
            <div className="content">{v.content}</div>
            <div className="time">{v.time.toLocaleTimeString()}</div>
          </li>
        ))}
      </ul>
    </div>
  )
}
